version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: imgm-postgres
    restart: always
    environment:
      POSTGRES_USER: imgm_user
      POSTGRES_PASSWORD: imgm_password
      POSTGRES_DB: imgm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
