[project]
name = "imgm-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maorophir", email = "maorophir@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "langchain-google-genai>=4.4.0",
    "langchain-ollama>=1.1.0",
    "langchain-postgres>=0.0.18",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.12",
    "langgraph-checkpoint-postgres>=3.1.2",
    "psycopg-pool>=3.3.3",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
imgm-ai = "imgm_ai.__main__:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "isort>=9.0.2",
]
