/**
 * Mock data for IMGM development.
 *
 * This file provides realistic game data and user reviews for building
 * the UI before we connect to IGDB and our own backend.
 *
 * Data shape mirrors what we'll get from production:
 *   - Game metadata → from IGDB API
 *   - ratings.imgm, aiSentiment, aiSummary → from our backend (ReviewAnalysis + GameAISummary)
 *   - ratings.metacritic/ign/steam → scraped or from external APIs
 *   - reviews → from our Reviews table
 */

export const mockGames = [
  {
    id: 11156,
    title: "Red Dead Redemption 2",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg",
    artworks: ["https://images.igdb.com/igdb/image/upload/t_1080p/ar56a.jpg"],
    description: "America, 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2018-10-26",
    genres: ["Adventure", "Shooter", "RPG"],
    platforms: ["PC", "PlayStation 4", "Xbox One"],
    ratings: {
      imgm: 9.7,
      metacritic: 97,
      ign: 10,
      steam: 91,
    },
    videos: [
      { name: "Launch Trailer", youtubeId: "gmA6MrX81z4" },
      { name: "Gameplay Reveal", youtubeId: "Dw_oH5oiUSE" },
    ],
    aiSentiment: "Positive",
    aiSummary: "Players universally praise the breathtaking open world and deeply emotional narrative. The attention to detail in environmental storytelling is frequently cited as unmatched in gaming. Some reviewers note the slow pacing in early chapters, but consider it a deliberate and rewarding design choice. The online mode receives mixed feelings compared to the single-player experience."
  },
  {
    id: 140301,
    title: "Age of Wonders 4",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co64z4.jpg",
    artworks: ["https://images.igdb.com/igdb/image/upload/t_1080p/ar1xtr.jpg"],
    description: "Rule a fantasy realm of your own design in Age of Wonders 4. Explore new magical realms in the ultimate blend of 4X strategy and turn-based tactical combat. Control a faction that evolves as you expand, with deep RPG character and army development.",
    developer: "Triumph Studios",
    publisher: "Paradox Interactive",
    releaseDate: "2023-05-02",
    genres: ["Strategy", "Turn-based strategy (TBS)", "Tactical"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    ratings: {
      imgm: 8.4,
      metacritic: 83,
      ign: 8.0,
      steam: 82,
    },
    videos: [
      { name: "Announcement Trailer", youtubeId: "3cPfjOT8MJk" },
    ],
    aiSentiment: "Positive",
    aiSummary: "Highly regarded for its deep empire-building mechanics and highly customizable faction creation system. Players love the freedom to create unique fantasy races. The tactical combat is praised as a significant improvement over previous entries. Some criticism around late-game repetitiveness and AI difficulty scaling."
  },
  {
    id: 19,
    title: "Warcraft III: Reign of Chaos",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y38.jpg",
    artworks: ["https://images.igdb.com/igdb/image/upload/t_1080p/ar54d.jpg"],
    description: "Warcraft III: Reign of Chaos is a high fantasy real-time strategy game. Players control heroes and armies from one of four races as they engage in a battle for the fate of the world of Azeroth.",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    releaseDate: "2002-07-03",
    genres: ["Strategy", "Real Time Strategy (RTS)"],
    platforms: ["PC", "Mac"],
    ratings: {
      imgm: 9.3,
      metacritic: 92,
      ign: 9.2,
    },
    videos: [
      { name: "Cinematic Trailer", youtubeId: "c2vm-QjK2xQ" },
    ],
    aiSentiment: "Positive",
    aiSummary: "A legendary RTS that shaped a generation, acclaimed for its hero units and gripping fantasy campaign. Reviewers consistently highlight the incredible story and genre-defining custom game scene. The legacy of its map editor and modding community is considered unmatched."
  },
  {
    id: 119133,
    title: "Elden Ring",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    artworks: ["https://images.igdb.com/igdb/image/upload/t_1080p/ar18y.jpg"],
    description: "Elden Ring is an action RPG developed by FromSoftware and published by Bandai Namco. The game was made in collaboration with fantasy novelist George R. R. Martin, who provided material for the game's setting. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    ratings: {
      imgm: 9.6,
      metacritic: 96,
      ign: 10,
      steam: 93,
    },
    videos: [
      { name: "Official Gameplay Trailer", youtubeId: "OT8if6DXOFQ" },
      { name: "Launch Trailer", youtubeId: "K_03kFqWfqs" },
    ],
    aiSentiment: "Positive",
    aiSummary: "Celebrated for its uncompromising combat and incredible world design, though some find it punishingly difficult. The open-world approach is seen as a masterful evolution of the Souls formula. Players consistently praise the sense of exploration and discovery. Criticisms focus on some late-game boss difficulty spikes and occasional performance issues on PC."
  },
  {
    id: 1877,
    title: "Cyberpunk 2077",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2mvt.jpg",
    artworks: ["https://images.igdb.com/igdb/image/upload/t_1080p/ar14i.jpg"],
    description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Shooter"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    ratings: {
      imgm: 8.6,
      metacritic: 86,
      ign: 9.0,
      steam: 85,
    },
    videos: [
      { name: "Official Launch Trailer", youtubeId: "UnA7tepsc7s" },
      { name: "Phantom Liberty Trailer", youtubeId: "SF8FE06Ld6g" },
    ],
    aiSentiment: "Mixed",
    aiSummary: "Following massive updates, players love the immersive city and story, but early technical flaws are still remembered. The Phantom Liberty expansion is widely considered a redemption arc. Night City itself is praised as one of the most atmospheric settings in gaming. The divide between launch-day players and post-patch players creates a unique split in sentiment."
  }
];

/**
 * Mock reviews — these simulate what we'd get from our Reviews + ReviewAnalysis tables.
 * Each review has an individual AI-analyzed sentiment.
 */
export const mockReviews = [
  // ── Red Dead Redemption 2 ──
  {
    id: 1,
    gameId: 11156,
    username: "WildWestFan",
    rating: 10,
    reviewText: "This is without a doubt the greatest game I've ever played. The world feels alive — every NPC has a routine, every town has a personality. Arthur Morgan's story had me genuinely emotional. Rockstar outdid themselves.",
    createdAt: "2024-08-12",
    sentiment: "Positive",
    hoursPlayed: "200+ hrs",
    platform: "PC",
    completionStatus: "100% Completed",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 10, gameplay: 9, graphics: 10, performance: 8 },
    recommendation: "Yes",
  },
  {
    id: 2,
    gameId: 11156,
    username: "CasualGamer_42",
    rating: 8,
    reviewText: "Beautiful game but the first few hours are painfully slow. I almost gave up before Chapter 3. Once it picks up though, it's incredible. Wish the online mode got more love.",
    createdAt: "2024-06-03",
    sentiment: "Mixed",
    hoursPlayed: "45 hrs",
    platform: "PlayStation 4",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 9, gameplay: 7, graphics: 9, performance: 7 },
    recommendation: "Yes",
  },
  {
    id: 3,
    gameId: 11156,
    username: "StoryDrivenPlayer",
    rating: 10,
    reviewText: "The attention to detail is insane. I spent hours just riding through the wilderness, hunting, and camping. The story is one of the best in any medium. A masterpiece.",
    createdAt: "2024-09-01",
    sentiment: "Positive",
    hoursPlayed: "120 hrs",
    platform: "Xbox One",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 10, gameplay: 10, graphics: 10, performance: 9 },
    recommendation: "Yes",
  },

  // ── Elden Ring ──
  {
    id: 4,
    gameId: 119133,
    username: "SoulsVeteran",
    rating: 10,
    reviewText: "FromSoftware took everything great about Dark Souls and dropped it into a massive open world. The exploration is unmatched. Every cave, every ruin has something interesting. Boss fights are spectacular.",
    createdAt: "2024-04-20",
    sentiment: "Positive",
    hoursPlayed: "300+ hrs",
    platform: "PC",
    completionStatus: "100% Completed",
    playStyle: "Solo",
    difficulty: "Hardcore",
    subScores: { story: 8, gameplay: 10, graphics: 9, performance: 8 },
    recommendation: "Yes",
  },
  {
    id: 5,
    gameId: 119133,
    username: "FirstTimeSouls",
    rating: 7,
    reviewText: "The game is gorgeous and the world is amazing to explore, but the difficulty is brutal. Some bosses feel unfair. I had to summon help for almost every major fight. Still enjoyed the journey though.",
    createdAt: "2024-07-15",
    sentiment: "Mixed",
    hoursPlayed: "60 hrs",
    platform: "PlayStation 5",
    completionStatus: "Finished Main Story",
    playStyle: "Co-op",
    difficulty: "Normal",
    subScores: { story: 6, gameplay: 7, graphics: 9, performance: 9 },
    recommendation: "Wait for a Sale",
  },
  {
    id: 6,
    gameId: 119133,
    username: "OpenWorldLover",
    rating: 9,
    reviewText: "Best open world since Breath of the Wild. The lack of quest markers actually makes exploration MORE fun, not less. You feel like a real adventurer discovering things organically.",
    createdAt: "2024-05-28",
    sentiment: "Positive",
    hoursPlayed: "150 hrs",
    platform: "Xbox Series X|S",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 7, gameplay: 10, graphics: 9, performance: 9 },
    recommendation: "Yes",
  },

  // ── Cyberpunk 2077 ──
  {
    id: 7,
    gameId: 1877,
    username: "NightCityResident",
    rating: 9,
    reviewText: "After the 2.0 update and Phantom Liberty, this is the game we were promised. Night City is the most immersive open world ever created. The story with Johnny Silverhand is unforgettable.",
    createdAt: "2024-03-10",
    sentiment: "Positive",
    hoursPlayed: "140 hrs",
    platform: "PC",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Hardcore",
    subScores: { story: 10, gameplay: 9, graphics: 10, performance: 8 },
    recommendation: "Yes",
  },
  {
    id: 8,
    gameId: 1877,
    username: "DayOnePlayer",
    rating: 6,
    reviewText: "I can't forget the launch. Yes, it's much better now, but the trust was broken. The game itself is good — great story, amazing world — but CDPR needs to be held accountable for the state it shipped in.",
    createdAt: "2024-01-22",
    sentiment: "Mixed",
    hoursPlayed: "30 hrs",
    platform: "PlayStation 4",
    completionStatus: "Dropped",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 8, gameplay: 6, graphics: 5, performance: 3 },
    recommendation: "Wait for a Sale",
  },
  {
    id: 9,
    gameId: 1877,
    username: "RPG_Enthusiast",
    rating: 9,
    reviewText: "Phantom Liberty is one of the best DLCs ever made. The spy thriller storyline is gripping, and the new area is packed with content. If you wrote this game off at launch, give it another chance.",
    createdAt: "2024-08-05",
    sentiment: "Positive",
    hoursPlayed: "85 hrs",
    platform: "PlayStation 5",
    completionStatus: "100% Completed",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 10, gameplay: 9, graphics: 9, performance: 9 },
    recommendation: "Yes",
  },

  // ── Age of Wonders 4 ──
  {
    id: 10,
    gameId: 140301,
    username: "4X_Strategist",
    rating: 9,
    reviewText: "The faction creator is a dream come true. I made a race of necromantic hobbits and it actually worked within the game's systems. The tactical combat is crunchy and satisfying. Best 4X of 2023.",
    createdAt: "2024-02-14",
    sentiment: "Positive",
    hoursPlayed: "200+ hrs",
    platform: "PC",
    completionStatus: "Still Playing",
    playStyle: "Multiplayer",
    difficulty: "Hardcore",
    subScores: { story: 5, gameplay: 10, graphics: 8, performance: 9 },
    recommendation: "Yes",
  },
  {
    id: 11,
    gameId: 140301,
    username: "CivFanatic",
    rating: 7,
    reviewText: "Good game but the late game drags. Once you've snowballed past a certain point, the remaining turns feel like a formality. Also wish there was more diplomatic depth. Still solid overall.",
    createdAt: "2024-05-20",
    sentiment: "Mixed",
    hoursPlayed: "50 hrs",
    platform: "PC",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 4, gameplay: 7, graphics: 7, performance: 8 },
    recommendation: "Wait for a Sale",
  },

  // ── Warcraft III ──
  {
    id: 12,
    gameId: 19,
    username: "ClassicGamer",
    rating: 10,
    reviewText: "This game defined my childhood. The campaign is one of the greatest ever made in an RTS. Arthas's fall is still one of gaming's best stories. And the custom games scene? Legendary.",
    createdAt: "2024-04-01",
    sentiment: "Positive",
    hoursPlayed: "500+ hrs",
    platform: "PC",
    completionStatus: "100% Completed",
    playStyle: "Multiplayer",
    difficulty: "Normal",
    subScores: { story: 10, gameplay: 10, graphics: 6, performance: 10 },
    recommendation: "Yes",
  },
  {
    id: 13,
    gameId: 19,
    username: "RTSNostalgia",
    rating: 9,
    reviewText: "Replayed this recently and it still holds up incredibly well. The hero system was revolutionary for its time. The mission variety is insane — base-building, RPG-style dungeon crawls, defense missions. A true classic.",
    createdAt: "2024-06-18",
    sentiment: "Positive",
    hoursPlayed: "100+ hrs",
    platform: "PC",
    completionStatus: "Finished Main Story",
    playStyle: "Solo",
    difficulty: "Normal",
    subScores: { story: 9, gameplay: 10, graphics: 5, performance: 10 },
    recommendation: "Yes",
  },
];